from my_types import SessionId
from suricate import Suricate

class CamController(object):
    def __init__(self, suricate) -> None: ...
    def evt_start_cam_ctrl(self): ...
    def evt_stop_cam_ctrl(self): ...
    def evt_move_cam(self, data): ...    
