from my_types import SessionId
from suricate import Suricate

class CamController(object):
    def start_cam_ctrl(self, suricate : Suricate): ...
    def stop_cam_ctrl(self): ...
    def move_cam(self): ...    
